

# to upload apk to firebase_app_distribution
# fastlane android firebase_distribution -----------------in terminal


default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:238148423303:android:656425f93fdd0bfcf07222",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        #firebase_cli_token: "1//039wBQC4Sr8-JCgYIARAAGAMSNwF-L9IrvbmfEGOFjVBKEekGCiH1FQr2fit21_XDYXmXWR1t1iKZCt7BYLWKlB52BYXmrse8QiQ",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mohamedelhosaraty05@gmail.com",
        release_notes: "First Fastlane Firebase Distribution",
        #release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end